stages:
  - lint_test

lint_test:
  stage: lint_test
  image: nixpkgs/nix-flakes:nixos-23.05
  script:
    - nix develop -c setup-drupal
    - nix develop -c composer phpcs
    - nix develop -c composer unit
